version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - ">=13"
  - dependency-name: concurrently
    versions:
    - 6.0.0
    - 6.0.1
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
    - 4.2.3
